### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by parkerlreed** [Two9A/robin-irc#2]
```
[parker@x3720 robin-irc]$ php robin-irc.php 
[20160407052325][IRC] Listening on port 8194
[20160407052337][IRC] Client connected
[20160407052337][IRC<-] CAP LS 302
PHP Fatal error:  Uncaught Error: Call to undefined function split() in /home/parker/build/robin-irc/robin-irc.php:353
Stack trace:
#0 /home/parker/build/robin-irc/robin-irc.php(121): Robin_IRC->__call('irc_CAP', Array)
#1 /home/parker/build/robin-irc/robin-irc.php(93): Robin_IRC->listen()
#2 /home/parker/build/robin-irc/robin-irc.php(616): Robin_IRC->__construct()
#3 {main}
  thrown in /home/parker/build/robin-irc/robin-irc.php on line 353
```

Hexchat config is as follows 

![1460006758](https://cloud.githubusercontent.com/assets/841440/14341411/b4d94282-fc5f-11e5-9496-1aa0dc0dd1e2.png)

**Comment by parkerlreed** [comment]
Forgot versions

Arch x86_64
php 7.0.5-1

**Comment by parkerlreed** [comment]
Compiled php5.5 and it tries to work but I get a few errors.

```
PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/parker/build/robin-irc/robin-irc.php on line 611
```

Also when I type /join #chat or any other channel it does nothing.

EDIT:

```
* Connected. Now logging in.
* Fetching token...
* Logged in to Reddit.
* Connected.
* Welcome to Robin/IRC bridge parkerlreed!parkerlreed@reddit.com
* PREFIX=(qov)~@+
* - reddit.com MOTD -
* - Current tally of votes
* - ----------------------
* -      2294 INCREASE
* -       666 CONTINUE
* - ----------------------
* -      2960 total users
* End of MOTD
 No channel joined. Try /join #<channel>
* PRAISE_NIGGERNIGGERS つ ͡◕ Ѿ ͡◕ ༽つ❥PRAISE u/NIGGERNIGGERS❥ლ(́◕◞Ѿ◟◕‵ლ)
 No channel joined. Try /join #<channel>
```

That's the only message that comes through. Terminal output shows a lot more.

**Comment by parkerlreed** [comment]
Works! 

![1460033298](https://cloud.githubusercontent.com/assets/841440/14351500/a138b756-fc9d-11e5-813c-d345dd7094ed.png)

**Comment by parkerlreed** [comment]
I just realized it's working on php7 now too. Thanks!
