### ISSUE TITLE
Possible message crash/connection issue

### ISSUE THREAD

**Issue by parkerlreed** [Two9A/robin-irc#4]
This has happened two times now.

```
[20160407164940][IRC->] :Grygon!Grygon@reddit.com PRIVMSG #general :ACTION voted to CONTINUE
[20160407164942][ROBIN<-] {"type": "chat", "payload": {"body": "$ snape was potions", "from": "hashtag_pickles"}}
[20160407164942][IRC->] :hashtag_pickles!hashtag_pickles@reddit.com PRIVMSG #trivia :snape was potions
[20160407164943][ROBIN<-] {"type": "join", "payload": {"user": "PraetorFaethor"}}
[20160407164943][ROBIN<-] {"type": "part", "payload": {"user": "xxajt1"}}
[20160407164943][IRC<-] PING LAG1459997783248
[20160407164943][IRC->] :localhost PONG reddit.com :LAG1459997783248
[20160407164943][ROBIN<-] {"type": "chat", "payload": {"body": "My own bot :D\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588 THERE ARE NO MORE GROUPS TO MERGE WITH! CHOOSE STAY! \u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588", "from": "Positrons"}}
[20160407164944][ROBIN<-] {"type": "chat", "payload": {"body": "%chat ConcernDoge", "from": "ArcOfDream"}}
[20160407164944][IRC->] :ArcOfDream!ArcOfDream@reddit.com PRIVMSG #chat :ConcernDoge
[20160407164944][ROBIN<-] {"type": "chat", "payload": {"body": "$ The answer was Gilderoy Lockhart! Correct users: (nobody) :(", "from": "npinsker"}}
[20160407164944][IRC->] :npinsker!npinsker@reddit.com PRIVMSG #trivia :The answer was Gilderoy Lockhart! Correct users: (nobody) :(
[20160407164944][ROBIN<-] {"type": "join", "payload": {"user": "xxajt1"}}
[20160407164944][ROBIN<-] {"type": "part", "payload": {"user": "p0wnxx0r"}}
[20160407164945][ROBIN<-] {"type": "chat", "payload": {"body": "^Biggest room or bust.", "from": "Koi-pond"}}
[20160407164945][IRC->] :Koi-pond!Koi-pond@reddit.com PRIVMSG #dev :Biggest room or bust.
[20160407164945][ROBIN<-] {"type": "join", "payload": {"user": "p0wnxx0r"}}
[20160407164945][ROBIN<-] {"type": "no_match", "payload": {}}
[20160407164945][IRC->] :localhost NOTICE #general :no compatible room found for matching, we will count votes and check again for a match in 1 minute.
[20160407164946][ROBIN<-] {"type": "chat", "payload": {"body": "* % \u3064 \u0361\u25d5 \u047e \u0361\u25d5 \u0f3d\u3064\u2765PRAISE u/NIGGERNIGGERS\u2765\u10da(\u0301\u25d5\u25de\u047e\u25df\u25d5\u2035\u10da)", "from": "PRAISE_NIGGERNIGGERS"}}
[20160407164946][IRC->] :PRAISE_NIGGERNIGGERS!PRAISE_NIGGERNIGGERS@reddit.com PRIVMSG #general :* % つ ͡◕ Ѿ ͡◕ ༽つ❥PRAISE u/NIGGERNIGGERS❥ლ(́◕◞Ѿ◟◕‵ლ)
[20160407164946][ROBIN<-] {"type": "chat", "payload": {"body": "#bard \ud835\udcd8 \ud835\udcfc\ud835\udcea\ud835\udd00 \ud835\udcf1\ud835\udcf8\ud835\udd00 \ud835\udcfc\ud835\udcf6\ud835\udcf8\ud835\udcf8\ud835\udcfd\ud835\udcf1 \ud835\udcfc\ud835\udcea\ud835\udcf7\ud835\udced \ud835\udcea\ud835\udcfb\ud835\udcee \ud835\udcfb\ud835\udcfe\ud835\udcfc\ud835\udcfd\ud835\udcf5\ud835\udcee\ud835\udced", "from": "ptrakk"}}
[20160407164946][ROBIN<-] {"type": "chat", "payload": {"body": "#rpg Round #3, 0 hits! Ja Noi HP: 171[\u2b1b\u2b1b\u2b1b\u2b1b\u2b1b] [2/6 to !flee] +XP: no one :(", "from": "barnum"}}
[20160407164946][IRC->] :barnum!barnum@reddit.com PRIVMSG #rpg :Round #3, 0 hits! Ja Noi HP: 171[⬛⬛⬛⬛⬛] [2/6 to !flee] +XP: no one :(
PHP Fatal error:  Uncaught WebSocket\ConnectionException: Empty read; connection dead?  Stream state: {"crypto":{"protocol":"TLSv1.2","cipher_name":"ECDHE-RSA-AES128-GCM-SHA256","cipher_bits":128,"cipher_version":"TLSv1\/SSLv3"},"timed_out":true,"blocked":true,"eof":false,"stream_type":"tcp_socket\/ssl","mode":"r+","unread_bytes":0,"seekable":false} in /home/parker/build/robin-irc/websocket/Base.php:269
Stack trace:
#0 /home/parker/build/robin-irc/websocket/Base.php(143): WebSocket\Base->read(2)
#1 /home/parker/build/robin-irc/websocket/Base.php(135): WebSocket\Base->receive_fragment()
#2 /home/parker/build/robin-irc/robin-irc.php(127): WebSocket\Base->receive()
#3 /home/parker/build/robin-irc/robin-irc.php(95): Robin_IRC->listen()
#4 /home/parker/build/robin-irc/robin-irc.php(618): Robin_IRC->__construct()
#5 {main}
  thrown in /home/parker/build/robin-irc/websocket/Base.php on line 269
```

It's possible that it may be my connection at work too. Just figured I would report this in case it was a reddit/script issue.

**Comment by Two9A** [comment]
I noticed this too, when the same line came through; probably some crazy Unicode making the script take a dump on itself.

OH WELL. :runner:
